### ISSUE TITLE
关于release_res()和request_res()两函数未声明就使用导致的bug

### ISSUE THREAD

**Issue by dvoprm** [presisco/EasyDrcom-OpenWRT#2]
在http://bbs.ghtt.net/thread-2042261-1-1.html里，
最后执行make -j1 V=s时，报错两函数使用前未声明，
经手动在【（我根据我的报错信息的出来的路径）SDK/build_dir/target-mips_34kc_uClibc-0.9.33.2/easydrcom/main.cpp】中将两函数定义提前，
最后成功。

**Comment by dvoprm** [comment]
我发现之前那个0.7我的路由器也能用，所以走了。

**Comment by presisco** [comment]
已经更改函数声明位置
